apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2022-05-17T14:24:25Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "207"
    uid: 580a9de7-4801-4a55-b5c7-82b5c4589b53
  spec:
    clusterIP: 10.61.0.1
    clusterIPs:
    - 10.61.0.1
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
    creationTimestamp: "2022-05-17T14:37:41Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: product-ctse
    name: product-ctse
    namespace: default
    resourceVersion: "7836"
    uid: 566925bb-23f7-4f2d-861f-aa5bdbe3f988
  spec:
    clusterIP: 10.61.2.228
    clusterIPs:
    - 10.61.2.228
    externalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 32105
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: product-ctse
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 34.100.237.25
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
